### ISSUE TITLE
I'm not able to build the CV as a page any more, It is stuck on an older commit

### ISSUE THREAD

**Issue by jkru3** [jitinnair1/autoCV#3]
<img width="1318" alt="Screen Shot 2022-11-24 at 12 20 54 AM" src="https://user-images.githubusercontent.com/98447888/203730281-57379e17-635c-4d5b-b64d-be227b67cb0d.png">

**Comment by jitinnair1** [comment]
Thank you for raising this issue. It could be due to the workflow not having permissions to write. I have added a note in the wiki [here (at Step 3)](https://github.com/jitinnair1/autoCV/wiki/How-to-use-autoCV:-Detailed-Instructions). Please let me know if this does not fix the issue.
